version: "3"
services:
  app:
    container_name: book_organizer_prd
    build:
      context: .
      dockerfile: ./.docker/development/Dockerfile
    command: bash -c "go run main.go"
    volumes:
      - .:/book-organizer
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - internal

  mongo:
    container_name: book_organizer_db
    image: mongo
    restart: always
    ports:
      - 27018:27017
    env_file:
      - .env.docker
    networks:
      - internal

networks:
  internal:
    driver: bridge
